### ISSUE TITLE
Back GitBook by a repo

### ISSUE THREAD

**Issue by backkem** [gortc/web#1]
I suggest to [back the GitBook by a repo](https://help.gitbook.com/github/can-i-host-on-github.html) so it can receive [pull requests](https://help.gitbook.com/books/how-to-collaborate-on-someone-else-s-book.html).

**Comment by ernado** [comment]
Actually, I want to consider another solution for documentation.
I want to make it self-hosted, so it can be available without the subdomain.
E.g. gortc.io/doc

Any ideas?

**Comment by backkem** [comment]
A quick search got me:

1. [Docusaurus](https://github.com/facebook/Docusaurus) ([demo](https://facebook.github.io/react-native/))
1. [docsify](docsify) ([demo](https://docsify.js.org))
1. [GitBook Toolchain](https://github.com/GitbookIO/gitbook) ([demo](https://tutorial.djangogirls.org/en/index.html)) seems abandoned thought.

**Comment by ernado** [comment]
Maybe it is better to use just github wiki for that

**Comment by backkem** [comment]
That seems like a good solution as well.

**Comment by ernado** [comment]
I will use github wiki if needed.
